version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: client-dev
    volumes:
      - ./client:/usr/local/app/client
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev
    volumes:
      - ./backend:/usr/local/app/backend
    ports:
      - "3001:3001"  # Adjust the port as needed
